server:
  port: ${port:8030}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${db_username:postgres}
    password: ${db_password:12345}
    url: ${db_url:jdbc:postgresql://localhost:5432/rolesdb}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql


debug: false